version: '3.8'

services:
  postgres:
    container_name: postgres-app_contenedor
    image: postgres:11
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=Libros
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
   

  pgadmin:
    container_name: pgadmin_postgres_app_contenedor
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "13001:80"
    depends_on:
      - postgres

volumes:
  db_data:
